Use a specific nightly toolchain as a workaround for building puzzlefs
Starting from nightly-2022-08-03, puzzlefs no longer builds because of
the following error:
error[E0407]: method `backtrace` is not a member of trait `std::error::Error`
  --> format/src/error.rs:13:10
   |
13 | #[derive(Error)]
   |          ^^^^^ not a member of trait `std::error::Error`
   |
   = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

Use nightly-2022-08-02 for now for lack of a better solution.

Signed-off-by: Ariel Miculas <amiculas@cisco.com>